export const COMPLIANCE_ERROR_CODES = {
  KYC_CASE_NOT_FOUND: 'COMPLIANCE_KYC_CASE_NOT_FOUND',
  KYC_ALREADY_SUBMITTED: 'COMPLIANCE_KYC_ALREADY_SUBMITTED',
  KYC_NOT_SUBMITTED: 'COMPLIANCE_KYC_NOT_SUBMITTED',
  KYC_DECISION_CONFLICT: 'COMPLIANCE_KYC_DECISION_CONFLICT',
  ELIGIBILITY_NOT_FOUND: 'COMPLIANCE_ELIGIBILITY_NOT_FOUND',
  SCREENING_NOT_FOUND: 'COMPLIANCE_SCREENING_NOT_FOUND',
  REGION_BLOCKED: 'COMPLIANCE_REGION_BLOCKED',
  RISK_FLAG_NOT_FOUND: 'COMPLIANCE_RISK_FLAG_NOT_FOUND',
  PROVIDER_ERROR: 'COMPLIANCE_PROVIDER_ERROR',
} as const
