export const IDENTITY_ERROR_CODES = {
  EMAIL_TAKEN: 'IDENTITY_EMAIL_TAKEN',
  WALLET_BOUND: 'IDENTITY_WALLET_BOUND',
  IDENTITY_NOT_FOUND: 'IDENTITY_NOT_FOUND',
  INVALID_VERIFICATION: 'INVALID_VERIFICATION_TOKEN',
  INVALID_SIGNATURE: 'INVALID_WALLET_SIGNATURE',
  NONCE_MISMATCH: 'WALLET_NONCE_MISMATCH',
  NONCE_EXPIRED: 'WALLET_NONCE_EXPIRED',
  VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  OAUTH_PROVIDER_UNSUPPORTED: 'OAUTH_PROVIDER_UNSUPPORTED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKED: 'SESSION_REVOKED',
} as const

export type IdentityErrorCode = (typeof IDENTITY_ERROR_CODES)[keyof typeof IDENTITY_ERROR_CODES]
